### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by ilatypov** [shinnn/get-spdx-license-ids#3]
What's the use case for this project and for the similar project https://github.com/shinnn/spdx-license-ids?  I see a list of licenses in the original spdx projects,

https://github.com/spdx/license-list

https://github.com/spdx/license-list-data/blob/master/json/licenses.json

**Comment by shinnn** [comment]
https://github.com/shinnn/spdx-license-ids/blob/5257c65ec2dd6d9335e0020fdf216bfdc8fcb936/build.js#L4
