### ISSUE TITLE
isDeprecatedLicenseId always false

### ISSUE THREAD

**Issue by kemitchell** [shinnn/get-spdx-license-ids#4]
It looks like the generator for <https://spdx.org/licenses/licenses.json> is currently setting `isDeprecatedLicenseId` to `false` for each and every identifier, including newly deprecated ones like `GPL-2.0`.

There may not be anything to do about it in this package, but I'm creating this issue, and linking it, to remind myself to review and PR if necessary, once it's sorted.

Related: https://github.com/spdx/tools/issues/144

**Comment by shinnn** [comment]
Seems fixed.
